
services:
  ci-portal:
    container_name: ci-portal
    build:
      context: .     # what to build 
    ports:
      - "8080:8080"          # Flask app exposed to host
    volumes:       #  for CI scripts
      - /var/run/docker.sock:/var/run/docker.sock  # for Docker deamon  access, run docker command
      - /home/itayraviv/Desktop/develeap_bootcamp26/tasks/python_week2/task2/flask-app:/mounted-serviceB #just for demo sholud be billing
      - /home/itayraviv/Desktop/develeap_bootcamp26/tasks/python_week2/client_tester:/mounted-serviceA # service whieght
    restart: unless-stopped
