
services:
  ci-portal:
    container_name: ci-portal
    build:
      context: .     # assumes your Dockerfile is here
    ports:
      - "8080:8080"          # Flask app exposed to host
    volumes:       # ✅ for CI scripts
      - /var/run/docker.sock:/var/run/docker.sock  # ✅ for Docker access
      - /home/itayraviv/Desktop/develeap_bootcamp26/tasks/python_week2/task2/flask-app:/mounted-app #just for demo
    restart: unless-stopped
