
services:
  db:
    container_name: weight_db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    networks:
      - shared-network
    volumes:
      - db_data:/var/lib/mysql
      - ./db_schemas/weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  weight-app:
    container_name: weight_service
    build: .
    ports:
      - "8082:5000"
    networks:
      - shared-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      FLASK_APP: app/weight.py
      FLASK_RUN_HOST: 0.0.0.0

volumes:
  db_data:

networks:
  shared-network:
    external: true

